version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # - .:/app
      - "${PHOTOS_PATH}:/app/uploads"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=sqlite:///./test.db
    command: pytest -v

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
