version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=sqlite:///./test.db
    command: pytest -v
